[package]
name = "secure-config"
version = "0.1.0"
authors = ["Viktor Lazarev <taurus101v@gmail.com>"]

[dependencies]
base64 = "0.9.0"
clap = "2.31"
failure = "0.1.1"
openssl = "0.10.5"
rand = "0.4.2"
rust-crypto = "0.2.36"
